### ISSUE TITLE
dependabot config?

### ISSUE THREAD

**Issue by mikehardy** [open-spaced-repetition/fsrs-rs#309]
Was updating deps in Anki-Android-Backend last couple days, playing with dependabot for the cargo ecosystem and noticed that the transitives coming from fsrs are stale

You might something like this, it's similar to the options I usually run with to keep the noise down, value-per-pull up while keeping major vers separate since those are the frequently problematic ones requiring forward-port touchups

`.github/dependabot.yml`

```yaml
version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
  groups:
    non-breaking:
      update-types:
        - "minor"
        - "patch"
  open-pull-requests-limit: 10
```

Obviously close if you are uninterested, just that I'd drop it in case it was useful
